/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC37XPD
 * - package : LQFP176
 */

#include "aurix_pin_mappings.h"


/* SMU pin configuration */

static const IfxPort_Io_ConfigPin smu_pin_table[] = 
{
    IFXCFG_P33_8_IO_CONFIG
};

static const IfxPort_Io_Config smu_io_config_table = 
{
    sizeof(smu_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)smu_pin_table
};

extern void smu_init_pins(void)
{
    IfxPort_Io_initModule(&smu_io_config_table);
}

