/**
**********************************************************************************************************************
*    @file           : uart.c
*    @brief          : uart setup body
*    @copyright Copyright (C) Infineon Technologies AG 2019
**********************************************************************************************************************
*
* Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
* business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
* are agreed, use of this file is subject to following:
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
* accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
* and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
* Software is furnished to do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including the above license grant, this restriction
* and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
* derivative works of the Software, unless such copies or derivative works are solely in the form of
* machine-executable object code generated by a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
* WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
* COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
* CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
* IN THE SOFTWARE.
*
**********************************************************************************************************************
*/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "string.h"
#include "uart.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define BAUDRATE                (115200)
#define RX_LINE                 IfxAsclin0_RXB_P15_3_IN                 /* UART0 receive port pin                    */
#define TX_LINE                 IfxAsclin0_TX_P15_2_OUT                 /* UART0 transmit port pin                   */

#define INTPRIO_ASCLIN0_TX      (19)                                    /* Definition of the interrupt priorities    */
#define UART_TX_BUFFER_SIZE     (255)                                   /* Definition of the transmit buffer size    */


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static IfxAsclin_Asc g_ascHandle;                                       /* Declaration of the ASC handle             */
static uint8 g_ascTxBuffer[UART_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8]; /* Declaration of the FIFOs parameters       */


/**
* @brief UART interrupt service routine
* @param argument: Not used
* @retval None
*/
IFX_INTERRUPT(asclin0_Tx_ISR, 0, INTPRIO_ASCLIN0_TX);                    /* Adding the Interrupt Service Routine    */
void asclin0_Tx_ISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_ascHandle);
}

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/**
* @brief UART interface initializarion
* @param argument: Not used
* @retval None
*/
void initASCLINUART(void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, TX_LINE.module);

    /* Set the desired baud rate */
    ascConfig.baudrate.baudrate = BAUDRATE;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN0_TX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &g_ascTxBuffer;
    ascConfig.txBufferSize = UART_TX_BUFFER_SIZE;

    /* Port pins configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,         IfxPort_InputMode_pullUp,               /* CTS pin not used                           */
        &RX_LINE,         IfxPort_InputMode_pullUp,               /* RX pin not used                            */
        NULL_PTR,         IfxPort_OutputMode_pushPull,            /* RTS pin not used                           */
        &TX_LINE,         IfxPort_OutputMode_pushPull,            /* TX pin                                     */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_ascHandle, &ascConfig);           /* Initialize module with above parameters    */
}

/**
* @brief UART print message to the serial port
* @param argument: char* message
* @retval None
*/
void writeASCLINUART(uint8 *message)
{
    Ifx_SizeT msg_len = strlen(message);                         /* Transmit data via TX                        */

    IfxAsclin_Asc_write(&g_ascHandle,
                        message,
                        &msg_len,
                        TIME_INFINITE
                        );
}
